#!/bin/sh

metapackage="`basename /var/lib/dpkg/info/mp-fremantle-*.list .list`"
communitymp="mp-fremantle-community-pr"
desktopdir=/usr/share/applications/hildon
desktopfile=$desktopdir/community-ssu-enabler.desktop
ssutmpdir=/opt/ssu
debfilename=mp-fremantle-community-pr_0_all.deb
debfile=$ssutmpdir/$debfilename

cleanup()
{
	if [ -f $desktopfile ];
		then
			rm -f $desktopfile
	fi
	if [ -f $debfile ];
		then
			rm -rf $ssutmpdir
	fi
}

if [ -f /var/lib/dpkg/info/$communitymp.list ]
then

cleanup
echo "Community SSU already enabled"
echo "Press any key to exit..."
read keypress
exit 0

else

if ps ax | grep -v grep | grep apt-worker > /dev/null
	then
		echo -e "Hildon Application Manager running, please exit it and press enter\c"
		read keypress
		killall apt-worker 2> /dev/null
		killall hildon-application-manager 2> /dev/null
		dpkg --configure -a
fi

if [ -f /var/lib/apt/lock ]
	then
		echo "apt status area locked, please exit all other apt instances then press enter (warning: apt will be killed)."
		read keypress
		killall apt-get 2> /dev/null
		rm /var/lib/apt/lock 2> /dev/null
		dpkg --configure -a
fi

if ps ax | grep -v grep | grep dpkg > /dev/null
	then
		echo "dpkg status area locked, please exit all other dpkg instances then press enter (warning: dpkg will be killed)."
		read keypress
		killall dpkg 2> /dev/null
		rm /var/lib/dpkg/lock 2> /dev/null
		dpkg --configure -a
fi

if [ ! "$metapackage" = "mp-fremantle-community-pr" ]
	then
		echo "Pinning Nokia package $metapackage dependencies..."
		metapackage_deps=$(apt-cache show $metapackage | grep Depends: | head -n 1 | perl -pe 's/Depends:\s+//; s/( \(.*?\))?, / /g;')
		echo "Marking [$metapackage_deps] as manually installed..."
		apt-get -y --force-yes install $metapackage_deps

		echo -e "Uninstalling Nokia package $metapackage..."
		dpkg -r $metapackage
fi

if [ -f /etc/apt/preferences ]
	then
		echo "\nSome packages are pinned in /etc/apt/preferences, this might prevent the upgrade, remove file? (Y/n)"
		read answer
		if [ "$answer" = "y" ] || [ "$answer" = "Y" ]
			then
				echo "Removing /etc/apt/preferences"
				rm /etc/apt/preferences
		elif [ "$answer" = "n" ] || [ "$answer" = "N" ]
			then echo "File not removed, installation might fail."
		else 
			echo "Removing /etc/apt/preferences"
			rm /etc/apt/preferences
		fi
fi

echo -e "\nInstalling community package $communitymp dumb meta package..."
dpkg -i --force-all $debfile

echo -e "\nUpdating repository lists..."
apt-get update

# Check if we have to install a kernel which workarounds errata 430973
# Assume upstream kernels support it
KERNEL_VERSION=`uname -r`
KERNEL_ERRATA_430973=1

case $KERNEL_VERSION in
	2.6.28*)
		if [ ! -f "/sys/kernel/errata_430973" ]
			then
				KERNEL_ERRATA_430973=0
		fi
	;;
	*)
	;;
esac

if [ "$?" = "0" ]
	then
		echo "backing up transistions.ini"
		mv /usr/share/hildon-desktop/transitions.ini /usr/share/hildon-desktop/transitions.ini.precssu
		if [ "$KERNEL_ERRATA_430973" = "0" ]
			then
				apt-get -y --force-yes install kernel-cssu kernel-cssu-modules kernel-cssu-flasher
				if [ "$?" = "0" ]
					then
						cleanup
						echo "Rebooting..."
						run-standalone.sh reboot
						while [ 1 ]; do sleep 1; done
				else
						echo "Community SSU enabled, but CSSU kernel installation failed."
						echo "Press any key to exit..."
						read keypress
				fi
		else
				echo "Community SSU successfully enabled. Launching Application Manager..."
				run-standalone.sh dbus-send --print-reply --type=method_call --dest=com.nokia.hildon_application_manager /com/nokia/hildon_application_manager com.nokia.hildon_application_manager.show_check_for_updates_view
				cleanup
				exit 0
		fi
	else
		echo "Community SSU enabled, but package was not installed. Errors have occured."
		echo "Press any key to exit..."
		read keypress
fi

fi
