#!/bin/sh

set -e

LICENSE=/tmp/.communityssu
DESKTOPDIR=/usr/share/applications/hildon
DESKTOPFILE=$DESKTOPDIR/community-ssu-enabler.desktop
HAMCFG=hildon-application-manager-config
APTWORKER=/usr/libexec/apt-worker
APTWORKER_SHIM=${APTWORKER}-cssu.sh

echo "Maemo 5 Community SSU release notes.

You are about to install a repository provided by the community,
this repository holds packages with patches added by the community at maemo.org

While these packages have been tested, installation is solely at your own risk.

After installation, launch the enabler from the menu and follow the onscreen instructions." > $LICENSE

echo "Please accept the license agreement displayed on your N900's screen."
maemo-confirm-text "Maemo 5 Community SSU Agreement" $LICENSE
rm -f $LICENSE

cat <<EOF | $HAMCFG -v add -
<config>
 <settings>
  <domain>
   <name>community-updates</name>
   <trust-level>650</trust-level>
   <key>3EF6EE85773B629FB2516B795D0E7C4F2E6D6F9A</key>
   <certified/>
  </domain>
 </settings>
</config>
EOF

$HAMCFG update

# Put a shim around apt-worker so that the 'ignore packages
# from wrong domains' flag is always turned off (defaults to
# on).
dpkg-divert --add --rename --divert "${APTWORKER}.real" "${APTWORKER}"
[ -L "${APTWORKER_SHIM}" ] || ln -s "${APTWORKER_SHIM}" "${APTWORKER}"

# Nokia repository signing key 1v1
apt-key add - <<HERE
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: SKS 1.1.0

mQGiBEzG2tIRBACC3/uryYwXSnzAHkaQOrVdN2P9qroZy1nHFkJAPO0b7TqPNsFxVhSwCF/3
XCVmmVBv3dL9uAimEgavUwIq0x3tLGn6OvpQ3BB/rIbZnkAaN6858jC4Ob/fA6SSoQPZ0GYn
pzD5MK3K4v44H+e+FpzTaGQmM4b/atkA/7xn4h0+OwCgslilNq/ZdbEPQz7MrleDiY2s2pUD
+wTeD3dYAdG/Z9i/OwgbEKimB4IFslXW/ye4MJPJKjst1nvyNiKT6KVOf+zpNdDgtV/aUJiw
MssObOkJZSar1OiNlrTZGBu7jwUD+fAG4YFI0c47ilMlwjn6Qq316nX1O7LvUk3S/cvqUlz4
6KY4E0/Cv96K7+FQVt1H0uA5pA51A/429Xf6Ei79a0PvGOUYHdiOsSN8WHHiSFSX5HeWNJ//
DQ2DaT2LDoabqV6/mGoztKg8HnPL2nG20GaKLn2MgzJezvQA0Uf1lRzt8Vq7iOPSAf+Tn7fL
nA8TBxj/Nns+VlDWQGzBeCB/R5HPB1KkkzMWLxG0bZUBVkjP2oQzW6/AdbRFbWFlbW8ub3Jn
IGNvbW11bml0eSByZXBvc2l0b3JpZXMgKGZyZW1hbnRsZSkgPHJlcG9zaXRvcmllc0BtYWVt
by5vcmc+iGAEExECACACGwMGCwkIBwMCBBUCCAMEFgIDAQIeAQIXgAUCUYuk/gAKCRBdDnxP
Lm1vmsz+AJ4wscU3h1l2oFQxGjVKYKLE8gdLiwCbBA7rZuQOpv5o4U2dSXo8QhB65USIZgQT
EQIAJgUCTMba0gIbAwUJBaOagAYLCQgHAwIEFQIIAwQWAgMBAh4BAheAAAoJEF0OfE8ubW+a
e/wAn3YQknNCIkY7B1TUsHlq69hE0HSCAJ93NtiL4tuH6R2flO5if4CFOK9pL7kCDQRMxtrS
EAgAqH6oplSN9coMxhAjfiQiAUWb64m8C6J1maYrkVJFE3415vLMTZINhCaI0cbF2ivxxyYS
bZ7Ok3QUMmCftqMBSqW6OaGeStiLpi1l/ufYUqZEflZ3aX+E4l7UMS52DmFO87q/k3NTbCzx
bJ9D8EZOd5pXLv0O9MSXtdT4K9tTkT/32h7MyH3uv69u82t/vaHyZJtGaKMJ7qs61GMkj3Kk
Sntlolu5JYsQJO57sPsyMWKUI4wD+onLmgVieWv+Q1bY+Gnm7C/G+lGYGOtQrP4dbyIB+0YZ
2WHXgVumQBJs6m56lRVxzsv6vt2NJ3SrJhfW77QuI8tI6gSIsKNfbMq1TwADBQf/Qf82J6BI
87ive0Qotx0BwgXlzPhQQ8r16jYhSlAk/26ZUioGRhJ7FuuGe/onAJgjv42yKQ+kH/+xLNNz
Tql5cje229EXDhAbbD6U4RtNv+OvSTagpvxQTasTPpVgG1u7PEhW9uYrvjj0lZXXjh0jP+iT
LAHgb4b6d9Ks/ak0Z400k1GShKNGquF10pPU3K4Bw+n0Sqeru2p/nG7x4oB9Hsv9O8H+Xh9D
DwsYGOYDDICQRs8jt0KbnhNpYPRhv1vT1sEq6cWWvNaLCJc2p0eVHSvv0rsVk7hB0J//3dWt
hd2kUfLJz2j5/PTGC27gr+1Pu73jDF3PQyCZEIoaEbA1oIhJBBgRAgAJAhsMBQJRi6WvAAoJ
EF0OfE8ubW+a7sYAnifGdevkFg8OBd3tSaKByfmfiDMsAJ41FJMi6sjcKcnjkHdaqqF5xlKr
RYhPBBgRAgAPBQJMxtrSAhsMBQkFo5qAAAoJEF0OfE8ubW+awdcAn08uXKiYsVByw6Z5Uqc2
yXNHtBgWAJoDKABTpSE4qUckr823pvlkfo8iLw==
=zTZI
-----END PGP PUBLIC KEY BLOCK-----
HERE

update-sudoers

if [ -f /var/lib/dpkg/info/mp-fremantle-community-pr.list ]
	then
		rm -f $DESKTOPFILE
fi

exit 0
