#!/bin/sh

set -e

if [ "$1" != "configure" ]; then exit 0; fi

if [ -f /var/lib/dpkg/info/mp-fremantle-community-pr.list ]; then
	rm -f /usr/share/applications/hildon/community-ssu-enabler.desktop
	rm -rf /opt/ssu
fi

# Replace user config Community SSU catalogues by system wide
if grep -q '<name>Community SSU</name>' /etc/hildon-application-manager/catalogues; then
hildon-application-manager-config -v delete - << EOF
<config>
 <catalogue>
  <file>community-ssu-catalogues</file>
  <id>community</id>
 </catalogue>
 <catalogue>
  <name>Community SSU</name>
  <uri>http://repository.maemo.org/community/</uri>
  <dist>fremantle</dist>
  <components>free non-free</components>
 </catalogue>
</config>
EOF
hildon-application-manager-config -v add - << EOF
<config>
 <catalogue>
  <file>community-ssu-catalogues</file>
  <id>community</id>
  <enabled/>
 </catalogue>
</config>
EOF
fi

if grep -q '<name>Community SSU (testing)</name>' /etc/hildon-application-manager/catalogues; then
hildon-application-manager-config -v delete - << EOF
<config>
 <catalogue>
  <file>community-ssu-catalogues</file>
  <id>community-testing</id>
 </catalogue>
 <catalogue>
  <name>Community SSU (testing)</name>
  <uri>http://repository.maemo.org/community-testing/</uri>
  <dist>fremantle</dist>
  <components>free non-free</components>
 </catalogue>
</config>
EOF
hildon-application-manager-config -v add - << EOF
<config>
 <catalogue>
  <file>community-ssu-catalogues</file>
  <id>community-testing</id>
  <enabled/>
 </catalogue>
</config>
EOF
fi

if grep -q '<name>Community SSU (devel)</name>' /etc/hildon-application-manager/catalogues; then
hildon-application-manager-config -v delete - << EOF
<config>
 <catalogue>
  <file>community-ssu-catalogues</file>
  <id>community-devel</id>
 </catalogue>
 <catalogue>
  <name>Community SSU (devel)</name>
  <uri>http://maemo.merlin1991.at/cssu/community-devel/</uri>
  <dist>fremantle</dist>
  <components>free non-free</components>
 </catalogue>
</config>
EOF
hildon-application-manager-config -v add - << EOF
<config>
 <catalogue>
  <file>community-ssu-catalogues</file>
  <id>community-devel</id>
  <enabled/>
 </catalogue>
</config>
EOF
fi

if grep -q '<name>Community SSU (thumb)</name>' /etc/hildon-application-manager/catalogues; then
hildon-application-manager-config -v delete - << EOF
<config>
 <catalogue>
  <file>community-ssu-catalogues</file>
  <id>community-thumb</id>
 </catalogue>
 <catalogue>
  <name>Community SSU (thumb)</name>
  <uri>http://maemo.merlin1991.at/cssu/community-thumb/</uri>
  <dist>fremantle</dist>
  <components>free non-free</components>
 </catalogue>
</config>
EOF
hildon-application-manager-config -v add - << EOF
<config>
 <catalogue>
  <file>community-ssu-catalogues</file>
  <id>community-thumb</id>
  <enabled/>
 </catalogue>
</config>
EOF
fi

for file in /usr/share/hildon-application-manager/keys/*.gpg; do
	apt-key add $file
done

hildon-application-manager-config update
update-sudoers

# Remove old diversion of apt-worker
APTWORKER=/usr/libexec/apt-worker
if [ -L "${APTWORKER}" ]; then
	rm -f "${APTWORKER}"
fi
if dpkg-divert --list | grep "${APTWORKER}"; then
	dpkg-divert --rename --remove "${APTWORKER}"
fi

exit 0
