#! /bin/sh

set -e

cat <<EOF | hildon-application-manager-config -v delete -
<config>
 <settings>
  <domain>
   <name>community-updates</name>
  </domain>
 </settings>
</config>
EOF

hildon-application-manager-config update

rm /usr/libexec/apt-worker
dpkg-divert --rename --remove /usr/libexec/apt-worker

apt-key del 2E6D6F9A || true
