#! /bin/sh

APTWORKER=/usr/libexec/apt-worker
set -e

cat <<EOF | hildon-application-manager-config -v delete -
<config>
 <settings>
  <domain>
   <name>community-updates</name>
  </domain>
 </settings>
</config>
EOF

hildon-application-manager-config update

[ -L "${APTWORKER}" ] && rm "${APTWORKER}"
dpkg-divert --rename --remove "${APTWORKER}"

apt-key del 2E6D6F9A || true
